package com.nicetech.optimus.utils;

import static com.nicetech.optimus.utils.RegexTest.TestarRegex;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;


public class GeraString {

    public static int getMesDoAno() {
        List<Integer> desconto = new ArrayList<>();
        desconto.add(1);
        desconto.add(2);
        desconto.add(3);
        desconto.add(4);
        desconto.add(5);
        desconto.add(6);
        desconto.add(7);
        desconto.add(9);
        desconto.add(10);
        desconto.add(11);
        desconto.add(12);
        Random ramdom = new Random();
        return desconto.get(ramdom.nextInt(desconto.size()));
    }

    public static int getAno() {
        List<Integer> desconto = new ArrayList<>();
        desconto.add(2_010);
        desconto.add(2_011);
        desconto.add(2_012);
        desconto.add(2_013);

        Random ramdom;
        ramdom = new Random();

        int string = desconto.get(ramdom.nextInt(desconto.size()));
        return string;
    }

    public String getStringQualquer() {
        // Determia as letras que poderão estar presente nas chaves
        String letras = "ABCDEFGHIJKLMNOPQRSTUVYWXZ";
        Random random = new Random();
        String armazenaChaves = "";
        for (int i = 0; i < 9; i++) {
            int index = random.nextInt(letras.length());
            armazenaChaves += letras.substring(index, index + 1);
        }
        return armazenaChaves;
    }

    public String getRg() {
        return "12.123.123-1";
    }

    public String getCpf() {

        return "265.576.657-15";
    }

    public String getCep() {
        String cep = "04872-290";
        if (TestarRegex(Regex.CEP, cep)) {
            return cep;
        }
        return "04872-290";
    }

    public String getCnpj() {
        String str = "49.765.854/0001-58";
        if (TestarRegex(Regex.CNPJ, str)) {
            return str;
        }
        return "111.111.111/111-11";
    }

    public String getEmail() {
        return "exemplo@exemplo.com";
    }

    public String getCidadeQualquer() {
        List<String> cidade = new ArrayList<>();
        cidade.add("São paulo");
        cidade.add("Rio de janeiro");
        Random ramdom = new Random();
        return cidade.get(ramdom.nextInt(cidade.size()));
    }

    public String getEmpresaQualquer() {
        List<String> lista = new ArrayList<>();
        lista.add("Alert Systems Sistemas Eletronicos Ltda");
        lista.add("Novatec Sistemas De Segurança ");
        lista.add("Atual Relogios De Ponto Ltda ");
        lista.add("Cati Rose Transporte De Passageiros Ltda");
        lista.add("G Eletro");
        lista.add("Emive Patrulha 24 Horas Ltda");
        lista.add("Hospital Militar ");
        lista.add("Helices Wind");
        lista.add("Emprotec");
        lista.add("R Johnson Servicos Ltda");
        lista.add("M Da Cunhya Telefonia");
        lista.add("Conexao Desenvolvimento Empresarial Ltda");
        lista.add("Wxm Tecnologia E Automaçao Ltda Me ");
        lista.add("Varosoft");
        lista.add("Smh Sistemas ");
        lista.add("Deals Ar Solutions");
        lista.add("Biotec Soluçoes Tecnologicas Ltda");
        lista.add("Grupo Detk");
        lista.add("Soft Graf Editora");
        lista.add("Kl Comercial ");
        lista.add("Qrnet Informatica");
        lista.add("Best Company Ltda");
        lista.add("World Connections ");
        lista.add("Digit On Line Eletro Eletronicos Ltda ");
        lista.add("Safdié Dtvm Ltda");
        lista.add("Via Tel");
        lista.add("Longsam Eletronicacomercial Ltda");
        lista.add("Drigom");
        lista.add("Jose Alves Prado Epp");
        lista.add("Auttec Tecnologia");
        lista.add("Ideal Home Automaçao");
        lista.add("Nobritech Tecnologia E Sistemas Ltda.");
        lista.add("Grupo Orion ");
        lista.add("Pontual  Jes Comercio E Assistencia Tecnica");
        lista.add("Ativats Tecnologia E Serviços De Informatica");
        lista.add("Evotec Soluçoes Tecnologicas");
        lista.add("Efficienty Engenharia E Tecnologia Ltda ");
        lista.add("Aportecltda");
        lista.add("Intrarec Construtora");
        lista.add("Sindicato Nacional Dos Aeroviarios - Sna");
        lista.add("Setsys Eletronica ");
        lista.add("Black Box Do Brasil Ind E Com Ltda");
        lista.add("Bom Market Com. Alim. Ltda");
        lista.add("Ocidntal Telecom");
        lista.add("3s Rastreadores ");
        lista.add("Smart Install");
        lista.add("Pacto Soluçoes Tecnologicas");
        lista.add("Dremar Segurança Eletronica");
        lista.add("Recognition Cia Bras. De Auto. Bancaria");
        lista.add("Csu Cardsystem");
        lista.add("Alarme Curitiba");
        lista.add("Olimac Comercio E Manutençao De Maquinas ");
        lista.add("Romep ");
        lista.add("Gocil Serviços De Segurançaltda");
        lista.add("Argon Industria E Comercio De Brindes ");
        lista.add("Rcm Comercio De Prod Al.");
        lista.add("Pratik Park Ltda");
        lista.add("Mando Machinery Dist. De Aut. Peças");
        lista.add("Florianocom. Alimentos");
        lista.add("Multialolloy");
        lista.add("Tecnoponto Sistemas /Lc Candido Informatica");
        lista.add("Condominio Acervo");
        lista.add("Intranet Consultoria");
        lista.add("Aprocon");
        lista.add("Motriz Instalaçaoes Eletromecanicas");
        lista.add("Infovix Comercialltda Me");
        lista.add("Hector");
        lista.add("Colegio Construarte");
        lista.add("Associaçao De Pais E Alunos Do Colegio Militar Dom Pedro Ii");
        Random ramdom = new Random();
        return lista.get(ramdom.nextInt(lista.size()));
    }

    public String getTelefoneQualquer() {
        List<String> lista = new ArrayList<>();
        lista.add("(11) 5090-0690");
        lista.add("(11) 5181-1318");
        lista.add("(61) 3354-9308");
        lista.add("(11) 4344-2055");
        lista.add("(11) 3866-1700");
        lista.add("(31) 3526-5193");
        lista.add("(11) 2915-1105");
        lista.add("(00) 3834-9950");
        lista.add("(11) 4224-2232");
        lista.add("(21) 2445-4007");
        lista.add("(00) 0000-0000");
        lista.add("(12) 3924-8524");
        lista.add("(13) 3278-1000");
        lista.add("(11) 3211-6030");
        lista.add("(11) 5060-5777");
        lista.add("(11) 3569-4469");
        lista.add("(84) 3316-0623");
        lista.add("(11) 4193-1730");
        lista.add("(11) 2984-8000");
        lista.add("(51) 3343-0090");
        lista.add("(73) 3605-2255");
        lista.add("(11) 3475-3600");
        lista.add("(01) 1359-6224");
        lista.add("(11) 4152-6447");
        lista.add("(11) 3096-1100");
        lista.add("(32) 3216-5080");
        lista.add("(11) 5091-2044");
        lista.add("(11) 7837-1516");
        lista.add("(34) 3303-2217");
        lista.add("(71) 3462-1336");
        lista.add("(51) 3051-2516");
        lista.add("(11) 5093-9651");
        lista.add("(61) 3314-1099");
        lista.add("(12) 3934-1905");
        lista.add("(00) 4329-3309");
        lista.add("(84) 2010-4151");
        lista.add("(81) 3031-6777");
        lista.add("(31) 3377-2556");
        lista.add("(11) 2147-1000");
        lista.add("(21) 2220-2016");
        lista.add("(02) 1386-0709");
        lista.add("(11) 4134-4024");
        lista.add("(21) 2747-2131");
        lista.add("(21) 2224-8212");
        lista.add("(11) 4186-9696");
        lista.add("(11) 9901-4909");
        lista.add("(00) 0000-0000");
        lista.add("(66) 3498-4545");
        lista.add("(11) 5508-4927");
        lista.add("(11) 2627-8913");
        lista.add("(41) 3079-4692");
        lista.add("(67) 3346-1625");
        lista.add("(01) 7323-3827");
        lista.add("(00) 0000-0000");
        lista.add("(11) 5014-4810");
        lista.add("(11) 3045-7686");
        lista.add("(11) 3168-9551");
        lista.add("(11) 3529-8752");
        lista.add("(11) 3079-3500");
        lista.add("(11) 4199-2354");
        lista.add("(62) 3581-5624");
        lista.add("(11) 4508-8420");
        lista.add("(11) 2147-1000");
        lista.add("(11) 5589-4625");
        lista.add("(11) 5565-5747");
        lista.add("(27) 3038-3503");
        lista.add("(11) 7739-1990");
        lista.add("(11) 5058-2775");
        Random ramdom = new Random();
        String numeroTelefone = lista.get(ramdom.nextInt(lista.size()));
        boolean validarTelefone = TestarRegex(Regex.TELEFONE, numeroTelefone);
        if (validarTelefone) {
            return numeroTelefone;
        }
        return "(99) 9999-9999";
    }

    public String getNomePordutoQualquer() {
        List<String> lista = new ArrayList<>();
        lista.add("Achocolatados");
        lista.add("Açúcar Confeiteiro   ");
        lista.add("Açúcar Mascavo   ");
        lista.add("Açúcar Refinado");
        lista.add("Adoçante");
        lista.add("Água");
        lista.add("Alcaparra   ");
        lista.add("Arroz");
        lista.add("Aspargo");
        lista.add("Aveia   ");
        lista.add("Azeite");
        lista.add("Azeitona");
        lista.add("Batata Palha");
        lista.add("Biscoitos");
        lista.add("Bolacha");
        lista.add("Café Em Pó");
        lista.add("Café Solúvel");
        lista.add("Caldo De Carne");
        lista.add("Caldo De Galinha");
        lista.add("Cereais Matinais");
        lista.add("Chás");
        lista.add("Chocolate Em Pó   ");
        lista.add("Coco Ralado");
        lista.add("Creme De Leite");
        lista.add("Ervas Aromáticas");
        lista.add("Essências Artificiais");
        lista.add("Extrato De Tomate");
        lista.add("Farinha De Mandioca");
        lista.add("Farinha De Milho");
        lista.add("Farinha De Rosca");
        lista.add("Farinha De Trigo");
        lista.add("Farinha Láctea   ");
        lista.add("Feijão");
        lista.add("Fermento");
        lista.add("Fubá");
        lista.add("Gelatinas");
        lista.add("Geléia");
        lista.add("Goiabada    ");
        lista.add("Iogurtes");
        lista.add("Ketchup");
        lista.add("Leite Condensado");
        lista.add("Leite De Coco");
        lista.add("Leite Em Pó    ");
        lista.add("Lingüiça");
        lista.add("Macarrão");
        lista.add("Macarrão Para Sopa");
        lista.add("Maionese");
        lista.add("Maisena");
        lista.add("Manjericão");
        lista.add("Manteiga");
        lista.add("Margarina");
        lista.add("Massas Frescas");
        lista.add("Massas Secas");
        lista.add("Milho");
        lista.add("Molho Inglês");
        lista.add("Molho Pronto");
        lista.add("Molhos De Pimenta");
        lista.add("Mostarda");
        lista.add("Óleo");
        lista.add("Orégano");
        lista.add("Ovos");
        lista.add("Palmito");
        lista.add("Pão De Forma");
        lista.add("Achocolatados");
        lista.add("Açúcar Confeiteiro   ");
        lista.add("Açúcar Mascavo   ");
        lista.add("Açúcar Refinado");
        lista.add("Adoçante");
        lista.add("Água");
        lista.add("Alcaparra   ");
        lista.add("Arroz");
        lista.add("Aspargo");
        lista.add("Aveia   ");
        lista.add("Azeite");
        lista.add("Azeitona");
        lista.add("Batata Palha");
        lista.add("Biscoitos");
        lista.add("Bolacha");
        lista.add("Café Em Pó");
        lista.add("Café Solúvel");
        lista.add("Caldo De Carne");
        lista.add("Caldo De Galinha");
        lista.add("Cereais Matinais");
        lista.add("Chás");
        lista.add("Chocolate Em Pó   ");
        lista.add("Coco Ralado");
        lista.add("Creme De Leite");
        lista.add("Ervas Aromáticas");
        lista.add("Essências Artificiais");
        lista.add("Extrato De Tomate");
        lista.add("Farinha De Mandioca");
        lista.add("Farinha De Milho");
        lista.add("Farinha De Rosca");
        lista.add("Farinha De Trigo");
        lista.add("Farinha Láctea   ");
        lista.add("Feijão");
        lista.add("Fermento");
        lista.add("Fubá");
        lista.add("Gelatinas");
        lista.add("Geléia");
        lista.add("Goiabada    ");
        lista.add("Iogurtes");
        lista.add("Ketchup");
        lista.add("Leite Condensado");
        lista.add("Leite De Coco");
        lista.add("Leite Em Pó    ");
        lista.add("Lingüiça");
        lista.add("Macarrão");
        lista.add("Macarrão Para Sopa");
        lista.add("Maionese");
        lista.add("Maisena");
        lista.add("Manjericão");
        lista.add("Manteiga");
        lista.add("Margarina");
        lista.add("Massas Frescas");
        lista.add("Massas Secas");
        lista.add("Milho");
        lista.add("Molho Inglês");
        lista.add("Molho Pronto");
        lista.add("Molhos De Pimenta");
        lista.add("Mostarda");
        lista.add("Óleo");
        lista.add("Orégano");
        lista.add("Ovos");
        lista.add("Palmito");
        lista.add("Pão De Forma");
        lista.add("Pêssego Em Calda");
        lista.add("Picles");
        lista.add("Pó Para Pudim    ");
        lista.add("Queijo Ralado");
        lista.add("Queijos");
        lista.add("Refrigerante");
        lista.add("Requeijão");
        lista.add("Sal");
        lista.add("Salame");
        lista.add("Salsicha");
        lista.add("Shoyo");
        lista.add("Sopas Prontas   ");
        lista.add("Temperos");
        lista.add("Vinagre");
        lista.add("Abacate  ");
        lista.add("Abacaxi");
        lista.add("Ameixa");
        lista.add("Banana");
        lista.add("Carambola");
        lista.add("Cenoura");
        lista.add("Cereja");
        lista.add("Figo");
        lista.add("Goiaba");
        lista.add("Jabuticaba");
        lista.add("Kiwi");
        lista.add("Laranja");
        lista.add("Limão  ");
        lista.add("Maçã");
        lista.add("Mamão");
        lista.add("Manga");
        lista.add("Maracujá ");
        lista.add("Melancia");
        lista.add("Melão");
        lista.add("Morango");
        lista.add("Pêra");
        lista.add("Pêssego");
        lista.add("Tangerina");
        lista.add("Uva");
        lista.add("Abóbora");
        lista.add("Acelga");
        lista.add("Agrião");
        lista.add("Alecrim");
        lista.add("Alface");
        lista.add("Alho");
        lista.add("Batata");
        lista.add("Batata Doce");
        lista.add("Berinjela");
        lista.add("Beterraba");
        lista.add("Brócolis");
        lista.add("Cebola");
        lista.add("Cebolinha");
        lista.add("Cheiro Verde");
        lista.add("Chuchu");
        lista.add("Coentro ");
        lista.add("Couve");
        lista.add("Escarola");
        lista.add("Espinafre");
        lista.add("Gengibre");
        lista.add("Hortelã");
        lista.add("Jiló");
        lista.add("Louro");
        lista.add("Mandioca");
        lista.add("Mandioquinha");
        lista.add("Pepino");
        lista.add("Pimentão");
        lista.add("Quiabo");
        lista.add("Rabanete");
        lista.add("Repolho");
        lista.add("Rúcula");
        lista.add("Salsa");
        lista.add("Salsão");
        lista.add("Tomate");
        lista.add("Vagem");
        lista.add("Acém");
        lista.add("Alcatra");
        lista.add("Anchova    ");
        lista.add("Asa De Frango    ");
        lista.add("Baby Beef");
        lista.add("Bacalhau    ");
        lista.add("Banha");
        lista.add("Bisteca");
        lista.add("Cação    ");
        lista.add("Camarão    ");
        lista.add("Caranguejo    ");
        lista.add("Carne Moída");
        lista.add("Carne Seca");
        lista.add("Carpaccio");
        lista.add("Cavala    ");
        lista.add("Cavalinha");
        lista.add("Chester    ");
        lista.add("Chorizo");
        lista.add("Contra Filé");
        lista.add("Coração    ");
        lista.add("Coração De Frango    ");
        lista.add("Costela");
        lista.add("Coxa De Chester");
        lista.add("Coxa E Sobrecoxa De Frango    ");
        lista.add("Coxão Duro");
        lista.add("Coxão Mole");
        lista.add("Coxinha De Asa    ");
        lista.add("Espetinho    ");
        lista.add("Espetinho Para Churrasco");
        lista.add("Filé De Frango    ");
        lista.add("File De Peixe    ");
        lista.add("Filé Mignon");
        lista.add("Fraldinha");
        lista.add("Frango À Passarinho    ");
        lista.add("Frango Inteiro   ");
        lista.add("Lagarto");
        lista.add("Lagosta    ");
        lista.add("Lagostim    ");
        lista.add("Linguado    ");
        lista.add("Lingüiça");
        lista.add("Lombo");
        lista.add("Lula    ");
        lista.add("Maminha");
        lista.add("Marisco    ");
        lista.add("Merluza    ");
        lista.add("Mexilhão");
        lista.add("Músculo");
        lista.add("Osso Buco");
        lista.add("Ostra    ");
        lista.add("Patinho");
        lista.add("Peito De Frango    ");
        lista.add("Pernil");
        lista.add("Peru");
        lista.add("Pescada    ");
        lista.add("Picanha");
        lista.add("Pintado    ");
        lista.add("Polvo    ");
        lista.add("Robalo    ");
        lista.add("Salmão    ");
        lista.add("Salsicha");
        lista.add("Siri    ");
        lista.add("Suína");
        lista.add("Tender");
        lista.add("Toucinho");
        lista.add("Truta");
        lista.add("Apresuntado");
        lista.add("Bacon    ");
        lista.add("Blaquet De Peru    ");
        lista.add("Copa    ");
        lista.add("Jambon    ");
        lista.add("Lombo Canadense    ");
        lista.add("Lombo Defumado    ");
        lista.add("Mortadela    ");
        lista.add("Mussarela");
        lista.add("Pastrami    ");
        lista.add("Patês    ");
        lista.add("Presunto    ");
        lista.add("Queijos    ");
        lista.add("Rosbife    ");
        lista.add("Salame    ");
        lista.add("Salsicha    ");
        lista.add("Sardella");
        lista.add("Sabão Em Pedra");
        lista.add("Água Sanitária");
        lista.add("Álcool");
        lista.add("Alvejantes    ");
        lista.add("Amaciante");
        lista.add("Anil    ");
        lista.add("Antimofo   ");
        lista.add("Cera Em Pasta    ");
        lista.add("Cera Liquida");
        lista.add("Desentupidor    ");
        lista.add("Desinfetante");
        lista.add("Desodorante Ambiental");
        lista.add("Detergente");
        lista.add("Esponja    ");
        lista.add("Esponja De Aço");
        lista.add("Graxa    ");
        lista.add("Inseticidas");
        lista.add("Limpa Assoalhos");
        lista.add("Limpa Carpete    ");
        lista.add("Limpa Forno    ");
        lista.add("Limpa Inox    ");
        lista.add("Limpa Prata");
        lista.add("Limpa Vidros    ");
        lista.add("Limpa-Tudo");
        lista.add("Lustra-Móveis");
        lista.add("Luvas");
        lista.add("Multiuso (Tipo Veja )   ");
        lista.add("Naftalina    ");
        lista.add("Óleo De Peroba    ");
        lista.add("Pá    ");
        lista.add("Palha De Aço    ");
        lista.add("Passa-Fácil");
        lista.add("Pregador");
        lista.add("Querosene    ");
        lista.add("Removedor    ");
        lista.add("Sabão De Coco");
        lista.add("Sabão Em Pedra    ");
        lista.add("Sabão Em Pó - Louças    ");
        lista.add("Sabão Em Pó - Roupas    ");
        lista.add("Saco De Lixo");
        lista.add("Sapólio");
        lista.add("Tira Ferrugem    ");
        lista.add("Tira-Mancha");
        lista.add("Sabonetes");
        lista.add("Absorvente   ");
        lista.add("Água Oxigenada");
        lista.add("Algodão");
        lista.add("Anticéptico Bucal   ");
        lista.add("Aparelhos Para Barba   ");
        lista.add("Barbeador Descartável");
        lista.add("Bronzeadores");
        lista.add("Bucha   ");
        lista.add("Colônias   ");
        lista.add("Condicionador");
        lista.add("Creme De Barbear");
        lista.add("Creme De Pele   ");
        lista.add("Creme Dental");
        lista.add("Desodorante");
        lista.add("Escova De Cabelos   ");
        lista.add("Escova De Dentes");
        lista.add("Esmaltes");
        lista.add("Esparadrapo");
        lista.add("Esponjas Para Banho  ");
        lista.add("Fio Dental");
        lista.add("Gaze ");
        lista.add("Hastes Flexíveis");
        lista.add("Hidratante   ");
        lista.add("Lamina De Barbear");
        lista.add("Lenços Umedecidos   ");
        lista.add("Lixa De Unha   ");
        lista.add("Loção Pós-Barba");
        lista.add("Maquiagem");
        lista.add("Mertiolate");
        lista.add("Óleo Após Banho   ");
        lista.add("Papel Higiênico   ");
        lista.add("Papel Toalha   ");
        lista.add("Perfumes   ");
        lista.add("Produtos De Beleza");
        lista.add("Removedor De Esmalte   ");
        lista.add("Repelentes   ");
        lista.add("Sabonete Líquido");
        lista.add("Sabonetes   ");
        lista.add("Talco");
        lista.add("Xampu");
        lista.add("Abridores De Garrafa    ");
        lista.add("Abridores De Lata    ");
        lista.add("Assadeiras    ");
        lista.add("Avental    ");
        lista.add("Bacia    ");
        lista.add("Balde   ");
        lista.add("Bandeja De Alumínio");
        lista.add("Cabides    ");
        lista.add("Canudos");
        lista.add("Copo Descartável    ");
        lista.add("Corda Para Varal    ");
        lista.add("Desentupidor");
        lista.add("Escova Lavar Roupas    ");
        lista.add("Esponja    ");
        lista.add("Estopa");
        lista.add("Filtro De Papel    ");
        lista.add("Fita Crepe ");
        lista.add("Fita Isolante");
        lista.add("Flanela    ");
        lista.add("Fósforo");
        lista.add("Guardanapos    ");
        lista.add("Isqueiros    ");
        lista.add("Lâmpadas");
        lista.add("Lanterna    ");
        lista.add("Luva    ");
        lista.add("Pá De Lixo");
        lista.add("Palito De Dente");
        lista.add("Panelas    ");
        lista.add("Pano De Chão    ");
        lista.add("Pano De Copa    ");
        lista.add("Papel Alumínio");
        lista.add("Papel Filme");
        lista.add("Papel Toalha");
        lista.add("Pegador De Panelas");
        lista.add("Perfex    ");
        lista.add("Pilha/Bateria");
        lista.add("Porta Filtro De Papel    ");
        lista.add("Pratos E Pratos Descartáveis");
        lista.add("Prendedor De Roupas    ");
        lista.add("Refil Aspirador De Pó    ");
        lista.add("Rodo    ");
        lista.add("Sacos De Lixo");
        lista.add("Sacos Para Microondas E Freezer    ");
        lista.add("Saquinho Para Freezer");
        lista.add("Tábua De Carne");
        lista.add("Tábua De Passar    ");
        lista.add("Talheres  E Abridores    ");
        lista.add("Tampa De Privada");
        lista.add("Tapete Para Banheiro/Porta");
        lista.add("Vassoura    ");
        lista.add("Vela");
        lista.add("Aspirador de pó");
        lista.add("Cafeteira");
        lista.add("Centrífuga");
        lista.add("Cortador de frios");
        lista.add("Chaleira elétrica");
        lista.add("Enceradeira");
        lista.add("Expremedor de frutas");
        lista.add("Exaustor ou coifa");
        lista.add("Ferro de passar");
        lista.add("Faca elétrica");
        lista.add("Fogão");
        lista.add("Freezer");
        lista.add("Forno de microondas");
        lista.add("Geladeira");
        lista.add("Grill sandwich");
        lista.add("Liquidificador");
        lista.add("Máquina de lavar louças");
        lista.add("Miniforno");
        lista.add("Panela elétrica");
        lista.add("Mix mixer");
        lista.add("Multifatiador");
        lista.add("Relógio de cozinha");
        lista.add("Secadoura de roupas");
        lista.add("Torradeira de pão ");
        lista.add("Conjunto de travessas refratarias");
        lista.add("Forma oval");
        lista.add("Forma retangular");
        lista.add("Bomboniere");
        lista.add("Jogo para feijoada");
        lista.add("Jogo de copos");
        lista.add("Petisqueiras");
        lista.add("Potes de codimento ");
        lista.add("Eletrônicos");
        lista.add("Aparelho de som");
        lista.add("Aquecedor");
        lista.add("Filmadora");
        lista.add("Despertador");
        lista.add("Telefone com secretaria eletrônica");
        lista.add("TV ");
        lista.add("Ventilador");
        lista.add("Aparelho de DVD");
        lista.add("Home-Theater");
        lista.add("Balança para cozinha");
        lista.add("Escada portátil");
        lista.add("Faqueiro - uso diário");
        lista.add("Faqueiro - uso especial");
        lista.add("Garrafa Térmica");
        lista.add("Grill para microondas");
        lista.add("Jogo de facas p/ cozinha");
        lista.add("Moedor de carne");
        lista.add("Fruteira");
        lista.add("Tabua p/ passar roupa");
        lista.add("Tabua p/ queijos e frios");
        lista.add("Vassoura mágica ");
        lista.add("Antiguidades ");
        lista.add("Esculturas");
        lista.add("Gravuras");
        lista.add("Quadros");
        lista.add("Tapetes");
        lista.add("Balança para cozinha");
        lista.add("Escada portátil");
        lista.add("Faqueiro - uso diário");
        lista.add("Faqueiro - uso especial");
        lista.add("Garrafa Térmica");
        lista.add("Grill para microondas");
        lista.add("Jogo de facas p/ cozinha");
        lista.add("Moedor de carne");
        lista.add("Fruteira");
        lista.add("Tabua p/ passar roupa");
        lista.add("Tabua p/ queijos e frios");
        lista.add("Vassoura mágica ");
        lista.add("Aparelho de fondue");
        lista.add("Jogo de Assadeiras");
        lista.add("Chaleira");
        lista.add("Conjunto de Panelas antiaderentes");
        lista.add("Forma de bolo");
        lista.add("Forma de pudim");
        lista.add("Forma de Suflê");
        lista.add("Forma de Torta");
        lista.add("Leiteira");
        lista.add("Panela Caçarola");
        lista.add("Panela de Pressão ");
        lista.add("Aparelho de Café");
        lista.add("Aparelho de Chá");
        lista.add("Aparelho de Jantar - uso diário");
        lista.add("Aparelho de Jantar - uso especial");
        lista.add("Jogo de copos");
        lista.add("Jogo para café da manhã");
        lista.add("Travessas ");
        lista.add("Baixela");
        lista.add("Balde de gelo");
        lista.add("Bandejas diversas");
        lista.add("Conjunto para bolo");
        lista.add("Coqueteleira");
        lista.add("Dosador de uísque");
        lista.add("Jogo p/ sobremesa");
        lista.add("Pinça p/ gelo");
        lista.add("Saladeiras ");
        Random ramdom = new Random();
        return lista.get(ramdom.nextInt(lista.size()));
    }

    public int getDescontoQualquer() {
        List<Integer> desconto = new ArrayList<>();
        desconto.add(10);
        desconto.add(20);
        desconto.add(30);
        desconto.add(40);
        desconto.add(50);
        desconto.add(60);
        desconto.add(70);
        Random ramdom = new Random();
        return desconto.get(ramdom.nextInt(desconto.size()));
    }

    public double getPrecoQualquer() {
        List<Double> preco = new ArrayList<>();
        preco.add(10.00);
        preco.add(15.00);
        preco.add(20.00);
        preco.add(25.00);
        preco.add(30.00);
        preco.add(35.00);
        preco.add(40.00);
        preco.add(45.00);
        preco.add(50.00);
        preco.add(55.00);
        preco.add(60.00);
        preco.add(65.00);
        preco.add(70.00);
        preco.add(75.00);
        preco.add(80.00);
        preco.add(85.00);
        preco.add(90.00);
        preco.add(95.00);
        preco.add(100.00);
        preco.add(110.00);
        preco.add(150.00);
        preco.add(170.00);
        Random ramdom = new Random();
        return preco.get(ramdom.nextInt(preco.size()));
    }

    public String getEstadoQualquer() {
        List<String> estado = new ArrayList<>();
        estado.add("SP");
        estado.add("RJ");
        Random ramdom = new Random();
        return estado.get(ramdom.nextInt(estado.size()));
    }

    public String getCategoriaQualquer() {
        List<String> categoria = new ArrayList<>();
        categoria.add("Beleza e Saúde");
        categoria.add("Comida e Bebida");
        categoria.add("Lazer e Turismo");
        categoria.add("Serviços");
        Random ramdom = new Random();
        return categoria.get(ramdom.nextInt(categoria.size()));
    }

    public String getNomeQualquer() {
        List<String> nome = new ArrayList<>();
        nome.add("Luiz");
        nome.add("Sandra");
        nome.add("Fabiana");
        nome.add("Gabi");
        nome.add("Iris");
        nome.add("Adinei Da Silva Lima");
        nome.add("Adriana Neves Barcelos");
        nome.add("Albert Nissimoff");
        nome.add("Alef Ferreira Da Silva");
        nome.add("Ana Carolina Silva Da Cruz");
        nome.add("Andrea Vieira Da Silva De Carvalho");
        nome.add("Andreia Isabel Da Silva");
        nome.add("Ariane Aparecida Arantes Fagundes");
        nome.add("Bruno Romio Ometto");
        nome.add("Caio Costa Limeira Dias");
        nome.add("Carlos Henrique Traldi Fidelis");
        nome.add("Caroline Da Conceicao Fontes");
        nome.add("Danielle Rodrigues De Lima");
        nome.add("David");
        nome.add("Deborah Corduro Kawahara");
        nome.add("Deyvid Franklin Araujo De Souza");
        nome.add("Diego Dos Santos Rodrigues");
        nome.add("Ederson Santos Silva");
        nome.add("Eduardo Da Silva Muniz");
        nome.add("Eduardo Fernandes Dos Santos");
        nome.add("Eric Augusto Batista Lemos");
        nome.add("Fabio Ferreira De Souza");
        nome.add("Felipe");
        nome.add("Fernanda Abriz");
        nome.add("Fernando Shigueo Ito");
        nome.add("Gabriela Arantes Leite");
        nome.add("Guilherme Bizerra Da Silva");
        nome.add("Hildebrando Santos Cardoso");
        nome.add("Janaina Tamara Simoes");
        nome.add("Joao Paulo Ferreira Nunes");
        nome.add("Joao Paulo Sales Costa");
        nome.add("Josue Araujo Santos");
        nome.add("Julia Maria Dos Santos");
        nome.add("Kaqpfm");
        nome.add("Leonardo Henrique Zanarolli De Oliveira");
        nome.add("Luana Pinho Teixeira");
        nome.add("Luciana Menezes Da Silva");
        nome.add("Lucinete Da Silva Cardoso");
        nome.add("Luiz Fillipe Santana Dos Reis");
        nome.add("Map");
        nome.add("Marcelo");
        nome.add("Marcelo Epstein");
        nome.add("Marcelo Vitor");
        nome.add("Maria Lindalva Freitas Lima");
        nome.add("Maria Solange Silva Bezerra");
        nome.add("Mariana Cristine Santos Rogerio");
        nome.add("Matheus Araujo Soares");
        nome.add("Paula Cristina Rocha De Araujo");
        nome.add("Philipe Siqueira Dos Santos");
        nome.add("Phillippe Dos Santos Lizardo");
        nome.add("Ricardo Oliveira Dias");
        nome.add("Roberta Inacio Da Silva");
        nome.add("Roberto");
        nome.add("Robson Maciel De Oliveira");
        nome.add("Sameila Iriana Borges Castilho");
        nome.add("Sidnei Lourenco Silva");
        nome.add("Silvania Miguel De Oliveira");
        nome.add("Silvia Morais Graciano");
        nome.add("Tatiane Moraes");
        nome.add("Teste");
        nome.add("Vitor Fusaro Fernandes");
        nome.add("Welyton Lima De Oliveira");
        nome.add("William Roberto De Araujo");
        nome.add("Yukio");
        Random ramdom = new Random();
        return nome.get(ramdom.nextInt(nome.size()));
    }
    private static final Logger LOG = getLogger(GeraString.class.getName());
}
