/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nicetech.optimus.view;

import com.nicetech.optimus.utils.Regex;
import com.nicetech.optimus.utils.TextTransfer;
import com.nicetech.optimus.utils.ValidaForm;
import java.awt.Color;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;

/**
 *
 * @author deyvid.souza
 */
public class CadastroClienteView extends javax.swing.JInternalFrame {

    public CadastroClienteView() {
        initComponents();
        this.getBtnUpdateUsuario().setVisible(false);
        this.getBtnDeleteUsuario().setEnabled(false);
        this.btnCadLogin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedDadosCadastrais = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        labNome = new javax.swing.JLabel();
        labRg = new javax.swing.JLabel();
        labCpf = new javax.swing.JLabel();
        labValidacao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        labTelefone = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        labCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComplemento = new javax.swing.JTextArea();
        txtBuscarUsers = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLoadUsers = new javax.swing.JTable();
        btnBuscarUsuario = new javax.swing.JButton();
        btnRegistroAnterior = new javax.swing.JButton();
        btnProximoRegistro = new javax.swing.JButton();
        jRadioButtonOrdenarPorNome = new javax.swing.JRadioButton();
        btnCadLogin = new javax.swing.JButton();
        btnDeleteUsuario = new javax.swing.JButton();
        btnUpdateUsuario = new javax.swing.JButton();
        btnInsertUsuario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        txtRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRgFocusLost(evt);
            }
        });
        txtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgActionPerformed(evt);
            }
        });

        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        labNome.setText("* Nome/Sobrenome");

        labRg.setText("* RG ");

        labCpf.setText("* CPF");

        labValidacao.setText("Por favor, preencha os campos marcados com \"*\"");

        jButton1.setText("Copiar cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(274, 274, 274)
                        .addComponent(jButton1)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(404, 404, 404))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labCpf)
                    .addComponent(labRg))
                .addGap(55, 55, 55))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCpf, txtNome, txtRg});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRg, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(labCpf)
                        .addGap(6, 6, 6)
                        .addComponent(txtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedDadosCadastrais.addTab("Dados *", jPanel2);

        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusLost(evt);
            }
        });
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        labTelefone.setText("* Telefone");

        labEmail.setText("* E-mail");

        jLabel11.setText("Site");

        txtSite.setEnabled(false);
        txtSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTelefone)
                    .addComponent(labEmail)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmail, txtSite, txtTelefone});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmail, txtSite, txtTelefone});

        jTabbedDadosCadastrais.addTab("Cotato *", jPanel3);

        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        jLabel3.setText("Bairro");

        jLabel4.setText("Rua");

        jLabel6.setText("Cidade");

        jLabel7.setText("Estado");

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Pais");

        labCep.setText("CEP");

        txtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCepFocusLost(evt);
            }
        });

        jLabel5.setText("Nº");

        jLabel14.setText("Complemento");

        txtComplemento.setColumns(20);
        txtComplemento.setRows(5);
        jScrollPane2.setViewportView(txtComplemento);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCep))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBairro, txtCep, txtCidade, txtEstado, txtNumero, txtPais, txtRua});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(labCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBairro, txtCep, txtCidade, txtEstado, txtNumero, txtPais, txtRua});

        jTabbedDadosCadastrais.addTab("Endereço", jPanel4);

        txtBuscarUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarUsersKeyPressed(evt);
            }
        });

        jTableLoadUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableLoadUsers.getTableHeader().setReorderingAllowed(false);
        jTableLoadUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLoadUsersMouseClicked(evt);
            }
        });
        jTableLoadUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableLoadUsersKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLoadUsers);

        btnBuscarUsuario.setText("Buscar - Nome / RG");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        btnRegistroAnterior.setText("<");
        btnRegistroAnterior.setToolTipText("Registro anterior");
        btnRegistroAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAnteriorActionPerformed(evt);
            }
        });

        btnProximoRegistro.setText(">");
        btnProximoRegistro.setToolTipText("Próximo registro  ");
        btnProximoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoRegistroActionPerformed(evt);
            }
        });

        jRadioButtonOrdenarPorNome.setText("A/Z");
        jRadioButtonOrdenarPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrdenarPorNomeActionPerformed(evt);
            }
        });
        jRadioButtonOrdenarPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButtonOrdenarPorNomeKeyPressed(evt);
            }
        });

        btnCadLogin.setText("Dados de acesso");
        btnCadLogin.setToolTipText("Altere aqui as permissões de acesso ao sistema.");
        btnCadLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadLoginActionPerformed(evt);
            }
        });

        btnDeleteUsuario.setText("Excluir");
        btnDeleteUsuario.setToolTipText("Após efetuar esta ação não será possível reverte-la.");
        btnDeleteUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUsuarioActionPerformed(evt);
            }
        });

        btnUpdateUsuario.setText("Salvar");
        btnUpdateUsuario.setToolTipText("Clique para salvar as alterações.");
        btnUpdateUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUsuarioActionPerformed(evt);
            }
        });

        btnInsertUsuario.setText("Salvar");
        btnInsertUsuario.setToolTipText("Clique para salvar as informações.");
        btnInsertUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTabbedDadosCadastrais, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsertUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtBuscarUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonOrdenarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(btnProximoRegistro))
                                    .addComponent(btnRegistroAnterior)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedDadosCadastrais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnInsertUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadLogin)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarUsuario)
                        .addComponent(jRadioButtonOrdenarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnProximoRegistro)
                        .addComponent(btnRegistroAnterior)))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if (!this.txtNome.getText().isEmpty()) {
            if (ValidaForm.isValid(this.txtNome.getText().trim(), true, Regex.NOME_E_SOBRENOME) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(0);
                labNome.setText("* Nome inválido");
                labNome.setForeground(Color.RED);
            } else {
                labNome.setText("* Nome completo");
                labNome.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (!this.txtNome.getText().isEmpty()) {
            if (ValidaForm.isValid(this.txtNome.getText().trim(), true, Regex.NOME_E_SOBRENOME) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(0);
                labNome.setText("* Nome inválido");
                labNome.setForeground(Color.RED);
            } else {
                labNome.setText("* Nome completo");
                labNome.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgActionPerformed

    private void txtRgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRgFocusLost
        if (!this.txtRg.getText().isEmpty()) {
            if (ValidaForm.isValid(this.txtRg.getText().trim(), true, Regex.RG) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(0);
                labRg.setText("* RG inválido");
                labRg.setForeground(Color.RED);
            } else {
                labRg.setText("* RG");
                labRg.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtRgFocusLost

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        if (!this.txtCpf.getText().isEmpty()) {
            if (ValidaForm.isValid(this.txtCpf.getText().trim(), true, Regex.CPF) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(0);
                labCpf.setText("* CPF inválido");
                labCpf.setForeground(Color.RED);
            } else {
                labCpf.setText("* CPF");
                labCpf.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtCpfFocusLost

    public void resetForm() {
        this.getTxtRg().setText(null);
        this.getTxtCpf().setText(null);
        this.getTxtNome().setText(null);
        this.getTxtBairro().setText(null);
        this.getTxtRua().setText(null);
        this.getTxtNumero().setText(null);
        this.getTxtComplemento().setText(null);
        this.getTxtCep().setText(null);
        this.getTxtCidade().setText(null);
        this.getTxtEstado().setText(null);
        this.getTxtPais().setText(null);
        this.getTxtTelefone().setText(null);
        this.getTxtEmail().setText(null);
        this.getTxtSite().setText(null);
    }
    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TextTransfer trans = new TextTransfer();
        trans.setClipboardContents(getTxtNome().getText() + "\t" + getTxtCpf().getText() + "\t" + getTxtRg().getText() + "\t" + getTxtTelefone().getText() + "\t" + getTxtEmail().getText() + "\t" + getTxtCidade().getText() + "\t" + getTxtEstado().getText() + "\t" + getTxtPais().getText() + "\t" + getTxtBairro().getText() + "\t" + getTxtRua().getText() + "\t" + getTxtNumero().getText() + "\t" + getTxtCep().getText() + "\t" + getTxtComplemento().getText() + "\t");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        if (!this.txtTelefone.getText().isEmpty()) {
            if (ValidaForm.isValid(this.txtTelefone.getText().trim(), true, Regex.TELEFONE) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(1);
                labTelefone.setText("* Telefone inválido");
                labTelefone.setForeground(Color.RED);
            } else {
                labTelefone.setText("* Telefone");
                labTelefone.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtTelefoneFocusLost

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed
        if (!this.txtTelefone.getText().isEmpty()) {
            if (ValidaForm.isValid(this.txtTelefone.getText(), true, Regex.TELEFONE) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(1);
                labTelefone.setText("* Telefone inválido");
                labTelefone.setForeground(Color.RED);
            } else {
                labTelefone.setText("* Telefone");
                labTelefone.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtTelefoneKeyPressed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (!this.txtEmail.getText().isEmpty()) {
            if (ValidaForm.isValid(this.txtEmail.getText().trim(), true, Regex.EMAIL) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(1);
                labEmail.setText("* E-mail inválido");
                labEmail.setForeground(Color.RED);
            } else {
                labEmail.setText("* E-mail");
                labEmail.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (!this.txtEmail.getText().trim().isEmpty()) {
            if (ValidaForm.isValid(this.txtEmail.getText().trim(), true, Regex.EMAIL) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(1);
                labEmail.setText("* E-mail inválido");
                labEmail.setForeground(Color.RED);
            } else {
                labEmail.setText("* E-mail");
                labEmail.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiteActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCepFocusLost
        if (!this.txtCep.getText().isEmpty()) {
            if (ValidaForm.isValid(this.txtCep.getText().trim(), true, Regex.CEP) == false) {
                this.getjTabbedDadosCadastrais().setSelectedIndex(2);
                labCep.setText("* CEP inválido");
                labCep.setForeground(Color.RED);
            } else {
                labCep.setText("* CEP");
                labCep.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtCepFocusLost

    private void txtBuscarUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsersKeyPressed


    }//GEN-LAST:event_txtBuscarUsersKeyPressed

    private void jTableLoadUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLoadUsersMouseClicked
        /*// Visibilidade dos botões.*/
        this.getBtnInsertUsuario().setVisible(false);
        this.getBtnInsertUsuario().setEnabled(false);
        this.getBtnUpdateUsuario().setVisible(true);
        this.getBtnUpdateUsuario().setEnabled(true);
        this.getBtnDeleteUsuario().setVisible(true);
        this.getBtnDeleteUsuario().setEnabled(true);
        this.btnCadLogin.setEnabled(true);
        /*// end */
        int linha_selecionada = this.getjTableLoadUsers().getSelectedRow();
        this.getTxtNome().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 0).toString());
        this.getTxtRg().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 1).toString());
        this.getTxtCpf().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 2).toString());
        this.getTxtTelefone().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 3).toString());
        this.getTxtEmail().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 4).toString());
        this.getTxtCidade().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 5).toString());
        this.getTxtEstado().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 6).toString());
        this.getTxtPais().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 7).toString());
        this.getTxtBairro().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 8).toString());
        this.getTxtRua().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 9).toString());
        this.getTxtNumero().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 10).toString());
        this.getTxtComplemento().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 11).toString());
        this.getTxtCep().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 12).toString());
        this.getTxtID().setText(this.getjTableLoadUsers().getValueAt(linha_selecionada, 13).toString());

        int indiceAtual = linha_selecionada;
        int numeroDeLinhas = getjTableLoadUsers().getRowCount() - 1;

        this.getBtnRegistroAnterior().setEnabled(true);
        this.getBtnProximoRegistro().setEnabled(true);

        if (indiceAtual == 0) {
            this.getBtnRegistroAnterior().setEnabled(false);
        }

        if (indiceAtual == numeroDeLinhas) {
            this.getBtnProximoRegistro().setEnabled(false);
        }
    }//GEN-LAST:event_jTableLoadUsersMouseClicked

    private void jTableLoadUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLoadUsersKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLoadUsersKeyPressed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed

    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnRegistroAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAnteriorActionPerformed

    }//GEN-LAST:event_btnRegistroAnteriorActionPerformed

    private void btnProximoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoRegistroActionPerformed

    }//GEN-LAST:event_btnProximoRegistroActionPerformed

    private void jRadioButtonOrdenarPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrdenarPorNomeActionPerformed

    }//GEN-LAST:event_jRadioButtonOrdenarPorNomeActionPerformed

    private void jRadioButtonOrdenarPorNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtonOrdenarPorNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOrdenarPorNomeKeyPressed

    private void btnCadLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadLoginActionPerformed

    }//GEN-LAST:event_btnCadLoginActionPerformed

    private void btnDeleteUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUsuarioActionPerformed

    }//GEN-LAST:event_btnDeleteUsuarioActionPerformed

    private void btnUpdateUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUsuarioActionPerformed

    }//GEN-LAST:event_btnUpdateUsuarioActionPerformed

    private void btnInsertUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertUsuarioActionPerformed

    }//GEN-LAST:event_btnInsertUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnCadLogin;
    private javax.swing.JButton btnDeleteUsuario;
    private javax.swing.JButton btnInsertUsuario;
    private javax.swing.JButton btnProximoRegistro;
    private javax.swing.JButton btnRegistroAnterior;
    private javax.swing.JButton btnUpdateUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonOrdenarPorNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedDadosCadastrais;
    private javax.swing.JTable jTableLoadUsers;
    private javax.swing.JLabel labCep;
    private javax.swing.JLabel labCpf;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labRg;
    private javax.swing.JLabel labTelefone;
    private javax.swing.JLabel labValidacao;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBuscarUsers;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextArea txtComplemento;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnBuscarUsuario() {
        return btnBuscarUsuario;
    }

    public void setBtnBuscarUsuario(javax.swing.JButton btnBuscarUsuario) {
        this.btnBuscarUsuario = btnBuscarUsuario;
    }

    public javax.swing.JButton getBtnDeleteUsuario() {
        return btnDeleteUsuario;
    }

    public void setBtnDeleteUsuario(javax.swing.JButton btnDeleteUsuario) {
        this.btnDeleteUsuario = btnDeleteUsuario;
    }

    public javax.swing.JButton getBtnInsertUsuario() {
        return btnInsertUsuario;
    }

    public void setBtnInsertUsuario(javax.swing.JButton btnInsertUsuario) {
        this.btnInsertUsuario = btnInsertUsuario;
    }

    public javax.swing.JButton getBtnUpdateUsuario() {
        return btnUpdateUsuario;
    }

    public void setBtnUpdateUsuario(javax.swing.JButton btnUpdateUsuario) {
        this.btnUpdateUsuario = btnUpdateUsuario;
    }

    public javax.swing.JLabel getjLabel1() {
        return labNome;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.labNome = jLabel1;
    }

    public javax.swing.JLabel getjLabel10() {
        return labEmail;
    }

    public void setjLabel10(javax.swing.JLabel jLabel10) {
        this.labEmail = jLabel10;
    }

    public javax.swing.JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(javax.swing.JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public javax.swing.JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(javax.swing.JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public javax.swing.JLabel getjLabel15() {
        return labCep;
    }

    public void setjLabel15(javax.swing.JLabel jLabel15) {
        this.labCep = jLabel15;
    }

    public javax.swing.JLabel getjLabel17() {
        return labRg;
    }

    public void setjLabel17(javax.swing.JLabel jLabel17) {
        this.labRg = jLabel17;
    }

    public javax.swing.JLabel getjLabel18() {
        return labCpf;
    }

    public void setjLabel18(javax.swing.JLabel jLabel18) {
        this.labCpf = jLabel18;
    }

    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public javax.swing.JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(javax.swing.JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public javax.swing.JLabel getjLabel9() {
        return labTelefone;
    }

    public void setjLabel9(javax.swing.JLabel jLabel9) {
        this.labTelefone = jLabel9;
    }

//    public javax.swing.JPanel getjPanel1() {
//        return jPanel1;
//    }
//    public void setjPanel1(javax.swing.JPanel jPanel1) {
//        this.jPanel1 = jPanel1;
//    }
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public javax.swing.JTabbedPane getjTabbedPane1() {
        return jTabbedDadosCadastrais;
    }

    public void setjTabbedPane1(javax.swing.JTabbedPane jTabbedPane1) {
        this.jTabbedDadosCadastrais = jTabbedPane1;
    }

    public javax.swing.JTable getjTableLoadUsers() {
        return jTableLoadUsers;
    }

    public void setjTableLoadUsers(javax.swing.JTable jTableLoadUsers) {
        this.jTableLoadUsers = jTableLoadUsers;
    }

    public javax.swing.JTextField getTxtBairro() {
        return txtBairro;
    }

    public void setTxtBairro(javax.swing.JTextField txtBairro) {
        this.txtBairro = txtBairro;
    }

    public javax.swing.JTextField getTxtBuscarUsers() {
        return txtBuscarUsers;
    }

    public void setTxtBuscarUsers(javax.swing.JTextField txtBuscarUsers) {
        this.txtBuscarUsers = txtBuscarUsers;
    }

    public javax.swing.JTextField getTxtCep() {
        return txtCep;
    }

    public void setTxtCep(javax.swing.JTextField txtCep) {
        this.txtCep = txtCep;
    }

    public javax.swing.JTextField getTxtCidade() {
        return txtCidade;
    }

    public void setTxtCidade(javax.swing.JTextField txtCidade) {
        this.txtCidade = txtCidade;
    }

    public javax.swing.JTextArea getTxtComplemento() {
        return txtComplemento;
    }

    public void setTxtComplemento(javax.swing.JTextArea txtComplemento) {
        this.txtComplemento = txtComplemento;
    }

    public javax.swing.JTextField getTxtCpf() {
        return txtCpf;
    }

    public void setTxtCpf(javax.swing.JTextField txtCpf) {
        this.txtCpf = txtCpf;
    }

    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(javax.swing.JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public javax.swing.JTextField getTxtEstado() {
        return txtEstado;
    }

    public void setTxtEstado(javax.swing.JTextField txtEstado) {
        this.txtEstado = txtEstado;
    }

    public javax.swing.JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(javax.swing.JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public javax.swing.JTextField getTxtNumero() {
        return txtNumero;
    }

    public void setTxtNumero(javax.swing.JTextField txtNumero) {
        this.txtNumero = txtNumero;
    }

    public javax.swing.JTextField getTxtPais() {
        return txtPais;
    }

    public void setTxtPais(javax.swing.JTextField txtPais) {
        this.txtPais = txtPais;
    }

    public javax.swing.JTextField getTxtRg() {
        return txtRg;
    }

    public void setTxtRg(javax.swing.JTextField txtRg) {
        this.txtRg = txtRg;
    }

    public javax.swing.JTextField getTxtRua() {
        return txtRua;
    }

    public void setTxtRua(javax.swing.JTextField txtRua) {
        this.txtRua = txtRua;
    }

    public javax.swing.JTextField getTxtSite() {
        return txtSite;
    }

    public void setTxtSite(javax.swing.JTextField txtSite) {
        this.txtSite = txtSite;
    }

    public javax.swing.JTextField getTxtTelefone() {
        return txtTelefone;
    }

    public void setTxtTelefone(javax.swing.JTextField txtTelefone) {
        this.txtTelefone = txtTelefone;
    }

    public javax.swing.JLabel getLabCpf() {
        return labCpf;
    }

    public void setLabCpf(javax.swing.JLabel labCpf) {
        this.labCpf = labCpf;
    }

    public javax.swing.JLabel getLabNome() {
        return labNome;
    }

    public void setLabNome(javax.swing.JLabel labNome) {
        this.labNome = labNome;
    }

    public javax.swing.JLabel getLabRg() {
        return labRg;
    }

    public void setLabRg(javax.swing.JLabel labRg) {
        this.labRg = labRg;
    }

    public javax.swing.JLabel getLabValidacao() {
        return labValidacao;
    }

    public void setLabValidacao(javax.swing.JLabel labValidacao) {
        this.labValidacao = labValidacao;
    }

    public javax.swing.JTabbedPane getjTabbedDadosCadastrais() {
        return jTabbedDadosCadastrais;
    }

    public void setjTabbedDadosCadastrais(javax.swing.JTabbedPane jTabbedDadosCadastrais) {
        this.jTabbedDadosCadastrais = jTabbedDadosCadastrais;
    }

    private javax.swing.JButton getBtnProximoRegistro() {
        return btnProximoRegistro;
    }

    private javax.swing.JButton getBtnRegistroAnterior() {
        return btnRegistroAnterior;
    }
    private static final Logger LOG = getLogger(CadastroClienteView.class.getName());

    /**
     * @return the txtID
     */
    public javax.swing.JTextField getTxtID() {
        return txtID;
    }

    /**
     * @param txtID the txtID to set
     */
    public void setTxtID(javax.swing.JTextField txtID) {
        this.txtID = txtID;
    }

}
