package com.nicetech.optimus.view;

import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;

public final class CadastroFornecedorView extends javax.swing.JInternalFrame {

    public CadastroFornecedorView() {
        initComponents();
        this.getBtnUpdateEmpresa().setVisible(false);
        this.getBtnDeletePJ().setVisible(false);
        this.getTxtID().setVisible(true);
        this.getTxtID().setText(Integer.toString(-1));
        this.getBtnLinkProduto().setVisible(true);
        this.btnPrintCadastro.setVisible(false);
        this.btnCadastroProduto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedDadosCadastrais = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtRazaoSocial = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        lblRazaoSocial = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        txtSetorAtuacao = new javax.swing.JTextField();
        lblSetorAtuacao = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        labValidacao = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSite = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComplemento = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        txtBuscaRegistro = new javax.swing.JTextField();
        btnBuscaRegistro = new javax.swing.JButton();
        btnInsertCadastro = new javax.swing.JButton();
        btnUpdateCadastro = new javax.swing.JButton();
        btnDeleteCadastro = new javax.swing.JButton();
        btnProximoRegistro = new javax.swing.JButton();
        btnRegistroAnterior = new javax.swing.JButton();
        rbtOrdenaRegistroPorNome = new javax.swing.JRadioButton();
        btnPrintAllCadastros = new javax.swing.JButton();
        btnCadastroProduto = new javax.swing.JButton();
        btnPrintCadastro = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Fornecedor");
        setToolTipText("Cadastro de Fornecedor");

        txtRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaoSocialActionPerformed(evt);
            }
        });

        lblRazaoSocial.setText("* Razão Social");

        lblCnpj.setText("* CNPJ");

        txtSetorAtuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetorAtuacaoActionPerformed(evt);
            }
        });

        lblSetorAtuacao.setText("Setor de atuação");

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        labValidacao.setText("Por favor, preencha os campos marcados com \"*\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetorAtuacao)
                    .addComponent(txtSetorAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(labValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCnpj, txtRazaoSocial, txtSetorAtuacao});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(labValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblCnpj)
                .addGap(6, 6, 6)
                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblSetorAtuacao)
                .addGap(6, 6, 6)
                .addComponent(txtSetorAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCnpj, txtRazaoSocial, txtSetorAtuacao});

        jTabbedDadosCadastrais.addTab("Dados", jPanel2);

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        lblTelefone.setText("* Telefone");

        lblEmail.setText("* E-mail");

        lblSite.setText("Site");

        txtSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addComponent(lblEmail)
                            .addComponent(lblSite))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtEmail)
                    .addComponent(txtSite))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedDadosCadastrais.addTab("Cotato", jPanel3);

        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        lblBairro.setText("Bairro");

        lblRua.setText("Rua");

        lblCidade.setText("Cidade");

        lblEstado.setText("Estado");

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        lblPais.setText("Pais");

        lblCep.setText("CEP");

        lblNumero.setText("Nº");

        lblComplemento.setText("Complemento");

        txtComplemento.setColumns(20);
        txtComplemento.setRows(5);
        jScrollPane1.setViewportView(txtComplemento);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado)
                            .addComponent(lblCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRua))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCep)
                            .addComponent(lblComplemento)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPais))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumero)
                                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblBairro)
                    .addComponent(lblCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado)
                    .addComponent(lblRua)
                    .addComponent(lblComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPais)
                            .addComponent(lblNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedDadosCadastrais.addTab("Endereço", jPanel4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Estado");

        jLabel2.setText("Cidade");

        jLabel3.setText("Mesorregião");

        jLabel4.setText("Microrregião");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(460, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3});

        jTabbedDadosCadastrais.addTab("Abrangência", jPanel5);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });
        jScrollPane2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane2ComponentAdded(evt);
            }
        });

        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Razão Social", "Setor de atuação", "Telefone", "E-mail", "Site", "Cidade", "Estado", "Pais", "Bairro", "Rua", "Nº", "Complemento", "Cep", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFornecedor.getTableHeader().setReorderingAllowed(false);
        jTableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFornecedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableFornecedor);

        txtBuscaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaRegistroActionPerformed(evt);
            }
        });
        txtBuscaRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaRegistroKeyPressed(evt);
            }
        });

        btnBuscaRegistro.setText("BUSCAR - Nome / CNPJ");
        btnBuscaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaRegistroActionPerformed(evt);
            }
        });
        btnBuscaRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscaRegistroKeyPressed(evt);
            }
        });

        btnInsertCadastro.setText("Salvar");
        btnInsertCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertCadastroActionPerformed(evt);
            }
        });

        btnUpdateCadastro.setText("Salvar");
        btnUpdateCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCadastroActionPerformed(evt);
            }
        });

        btnDeleteCadastro.setText("Excluir");
        btnDeleteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCadastroActionPerformed(evt);
            }
        });

        btnProximoRegistro.setText(">");
        btnProximoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProximoRegistroMouseClicked(evt);
            }
        });
        btnProximoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoRegistroActionPerformed(evt);
            }
        });

        btnRegistroAnterior.setText("<");
        btnRegistroAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAnteriorActionPerformed(evt);
            }
        });

        rbtOrdenaRegistroPorNome.setText("A/Z");
        rbtOrdenaRegistroPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOrdenaRegistroPorNomeActionPerformed(evt);
            }
        });
        rbtOrdenaRegistroPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtOrdenaRegistroPorNomeKeyPressed(evt);
            }
        });

        btnPrintAllCadastros.setText("Imprimir Tudo");
        btnPrintAllCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintAllCadastrosMouseClicked(evt);
            }
        });
        btnPrintAllCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintAllCadastrosActionPerformed(evt);
            }
        });

        btnCadastroProduto.setText(" Produtos");
        btnCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProdutoActionPerformed(evt);
            }
        });

        btnPrintCadastro.setText("Imprimir");
        btnPrintCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtBuscaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscaRegistro)
                        .addGap(10, 10, 10)
                        .addComponent(rbtOrdenaRegistroPorNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistroAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProximoRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrintAllCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedDadosCadastrais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPrintCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscaRegistro, btnCadastroProduto, btnDeleteCadastro, btnInsertCadastro, btnPrintAllCadastros, btnPrintCadastro, btnUpdateCadastro});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedDadosCadastrais, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnUpdateCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrintCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastroProduto)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscaRegistro)
                            .addComponent(txtBuscaRegistro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistroAnterior)
                            .addComponent(btnProximoRegistro)
                            .addComponent(rbtOrdenaRegistroPorNome)
                            .addComponent(btnPrintAllCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscaRegistro, btnCadastroProduto, btnDeleteCadastro, btnInsertCadastro, btnPrintAllCadastros, btnPrintCadastro, btnUpdateCadastro});

        jTabbedDadosCadastrais.getAccessibleContext().setAccessibleName("Dado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaoSocialActionPerformed

    private void txtSetorAtuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetorAtuacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorAtuacaoActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiteActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void jTableFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMouseClicked

    }//GEN-LAST:event_jTableFornecedorMouseClicked

    private void btnBuscaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaRegistroActionPerformed

    }//GEN-LAST:event_btnBuscaRegistroActionPerformed

    private void btnInsertCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertCadastroActionPerformed

    }//GEN-LAST:event_btnInsertCadastroActionPerformed

    private void btnUpdateCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCadastroActionPerformed

    }//GEN-LAST:event_btnUpdateCadastroActionPerformed

    private void btnDeleteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCadastroActionPerformed

    }//GEN-LAST:event_btnDeleteCadastroActionPerformed

    private void txtBuscaRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaRegistroKeyPressed

    }//GEN-LAST:event_txtBuscaRegistroKeyPressed

    private void btnProximoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoRegistroActionPerformed


    }//GEN-LAST:event_btnProximoRegistroActionPerformed

    private void btnRegistroAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAnteriorActionPerformed

    }//GEN-LAST:event_btnRegistroAnteriorActionPerformed

    private void txtBuscaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaRegistroActionPerformed

    private void jScrollPane2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2ComponentAdded

    private void btnPrintAllCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintAllCadastrosActionPerformed

    }//GEN-LAST:event_btnPrintAllCadastrosActionPerformed

    private void btnPrintAllCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintAllCadastrosMouseClicked
    }//GEN-LAST:event_btnPrintAllCadastrosMouseClicked

    private void rbtOrdenaRegistroPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOrdenaRegistroPorNomeActionPerformed

    }//GEN-LAST:event_rbtOrdenaRegistroPorNomeActionPerformed

    private void rbtOrdenaRegistroPorNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtOrdenaRegistroPorNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtOrdenaRegistroPorNomeKeyPressed

    private void btnPrintCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintCadastroActionPerformed

    }//GEN-LAST:event_btnPrintCadastroActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProdutoActionPerformed
        CadastroProdutoView frmCadastroProduto = new CadastroProdutoView(this);
        getDesktopPane().add(frmCadastroProduto);
        moveToBack();
    }//GEN-LAST:event_btnCadastroProdutoActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void btnProximoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximoRegistroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProximoRegistroMouseClicked

    private void btnBuscaRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscaRegistroKeyPressed

    }//GEN-LAST:event_btnBuscaRegistroKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaRegistro;
    private javax.swing.JButton btnCadastroProduto;
    private javax.swing.JButton btnDeleteCadastro;
    private javax.swing.JButton btnInsertCadastro;
    private javax.swing.JButton btnPrintAllCadastros;
    private javax.swing.JButton btnPrintCadastro;
    private javax.swing.JButton btnProximoRegistro;
    private javax.swing.JButton btnRegistroAnterior;
    private javax.swing.JButton btnUpdateCadastro;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedDadosCadastrais;
    private javax.swing.JTable jTableFornecedor;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labValidacao;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSetorAtuacao;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JRadioButton rbtOrdenaRegistroPorNome;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBuscaRegistro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextArea txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSetorAtuacao;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnDeletePJ() {
        return btnDeleteCadastro;
    }

    public void setBtnDeletePJ(javax.swing.JButton btnDeletePJ) {
        this.btnDeleteCadastro = btnDeletePJ;
    }

    public javax.swing.JButton getBtnInsertEmpresa() {
        return btnInsertCadastro;
    }

    public void setBtnInsertEmpresa(javax.swing.JButton btnInsertEmpresa) {
        this.btnInsertCadastro = btnInsertEmpresa;
    }

    public javax.swing.JButton getBtnUpdateEmpresa() {
        return btnUpdateCadastro;
    }

    public void setBtnUpdateEmpresa(javax.swing.JButton btnUpdateEmpresa) {
        this.btnUpdateCadastro = btnUpdateEmpresa;
    }

    public javax.swing.JLabel getjLabel1() {
        return lblRazaoSocial;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.lblRazaoSocial = jLabel1;
    }

    public javax.swing.JLabel getjLabel10() {
        return lblEmail;
    }

    public void setjLabel10(javax.swing.JLabel jLabel10) {
        this.lblEmail = jLabel10;
    }

    public javax.swing.JLabel getjLabel11() {
        return lblSite;
    }

    public void setjLabel11(javax.swing.JLabel jLabel11) {
        this.lblSite = jLabel11;
    }

    public javax.swing.JLabel getjLabel13() {
        return lblSetorAtuacao;
    }

    public void setjLabel13(javax.swing.JLabel jLabel13) {
        this.lblSetorAtuacao = jLabel13;
    }

    public javax.swing.JLabel getjLabel14() {
        return lblComplemento;
    }

    public void setjLabel14(javax.swing.JLabel jLabel14) {
        this.lblComplemento = jLabel14;
    }

    public javax.swing.JLabel getjLabel15() {
        return lblCep;
    }

    public void setjLabel15(javax.swing.JLabel jLabel15) {
        this.lblCep = jLabel15;
    }

    public javax.swing.JLabel getjLabel2() {
        return lblCnpj;
    }

    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.lblCnpj = jLabel2;
    }

    public javax.swing.JLabel getjLabel3() {
        return lblBairro;
    }

    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.lblBairro = jLabel3;
    }

    public javax.swing.JLabel getjLabel4() {
        return lblRua;
    }

    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.lblRua = jLabel4;
    }

    public javax.swing.JLabel getjLabel5() {
        return lblNumero;
    }

    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.lblNumero = jLabel5;
    }

    public javax.swing.JLabel getjLabel6() {
        return lblCidade;
    }

    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.lblCidade = jLabel6;
    }

    public javax.swing.JLabel getjLabel7() {
        return lblEstado;
    }

    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.lblEstado = jLabel7;
    }

    public javax.swing.JLabel getjLabel8() {
        return lblPais;
    }

    public void setjLabel8(javax.swing.JLabel jLabel8) {
        this.lblPais = jLabel8;
    }

    public javax.swing.JLabel getjLabel9() {
        return lblTelefone;
    }

    public void setjLabel9(javax.swing.JLabel jLabel9) {
        this.lblTelefone = jLabel9;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public javax.swing.JTabbedPane getjTabbedPane1() {
        return jTabbedDadosCadastrais;
    }

    public void setjTabbedPane1(javax.swing.JTabbedPane jTabbedPane1) {
        this.jTabbedDadosCadastrais = jTabbedPane1;
    }

    public javax.swing.JTable getjTableFornecedor() {
        return jTableFornecedor;
    }

    public void setjTableFornecedor(javax.swing.JTable jTableFornecedor) {
        this.jTableFornecedor = jTableFornecedor;
    }

    public javax.swing.JTextField getTxtBairro() {
        return txtBairro;
    }

    public void setTxtBairro(javax.swing.JTextField txtBairro) {
        this.txtBairro = txtBairro;
    }

    public javax.swing.JTextField getTxtBuscar() {
        return txtBuscaRegistro;
    }

    public void setTxtBuscar(javax.swing.JTextField txtBuscar) {
        this.txtBuscaRegistro = txtBuscar;
    }

    public javax.swing.JTextField getTxtCep() {
        return txtCep;
    }

    public void setTxtCep(javax.swing.JTextField txtCep) {
        this.txtCep = txtCep;
    }

    public javax.swing.JTextField getTxtCidade() {
        return txtCidade;
    }

    public void setTxtCidade(javax.swing.JTextField txtCidade) {
        this.txtCidade = txtCidade;
    }

    public javax.swing.JTextField getTxtCnpj() {
        return txtCnpj;
    }

    public void setTxtCnpj(javax.swing.JTextField txtCnpj) {
        this.txtCnpj = txtCnpj;
    }

    public javax.swing.JTextArea getTxtComplemento() {
        return txtComplemento;
    }

    public void setTxtComplemento(javax.swing.JTextArea txtComplemento) {
        this.txtComplemento = txtComplemento;
    }

    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(javax.swing.JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public javax.swing.JTextField getTxtEstado() {
        return txtEstado;
    }

    public void setTxtEstado(javax.swing.JTextField txtEstado) {
        this.txtEstado = txtEstado;
    }

    public javax.swing.JTextField getTxtID() {
        return txtID;
    }

    public void setTxtID(javax.swing.JTextField txtID) {
        this.txtID = txtID;
    }

    public javax.swing.JTextField getTxtNumero() {
        return txtNumero;
    }

    public void setTxtNumero(javax.swing.JTextField txtNumero) {
        this.txtNumero = txtNumero;
    }

    public javax.swing.JTextField getTxtPais() {
        return txtPais;
    }

    public void setTxtPais(javax.swing.JTextField txtPais) {
        this.txtPais = txtPais;
    }

    public javax.swing.JTextField getTxtRua() {
        return txtRua;
    }

    public void setTxtRua(javax.swing.JTextField txtRua) {
        this.txtRua = txtRua;
    }

    public javax.swing.JTextField getTxtSite() {
        return txtSite;
    }

    public void setTxtSite(javax.swing.JTextField txtSite) {
        this.txtSite = txtSite;
    }

    public javax.swing.JTextField getTxtTelefone() {
        return txtTelefone;
    }

    public void setTxtTelefone(javax.swing.JTextField txtTelefone) {
        this.txtTelefone = txtTelefone;
    }

    public javax.swing.JLabel getLabValidacao() {
        return labValidacao;
    }

    public void setLabValidacao(javax.swing.JLabel labValidacao) {
        this.labValidacao = labValidacao;
    }

    public javax.swing.JTabbedPane getjTabbedDadosCadastrais() {
        return jTabbedDadosCadastrais;
    }

    public void setjTabbedDadosCadastrais(javax.swing.JTabbedPane jTabbedDadosCadastrais) {
        this.jTabbedDadosCadastrais = jTabbedDadosCadastrais;
    }

    public javax.swing.JButton getBtnLinkProduto() {
        return btnPrintAllCadastros;
    }

    public void setBtnLinkProduto(javax.swing.JButton btnLinkProduto) {
        this.btnPrintAllCadastros = btnLinkProduto;
    }

    public javax.swing.JButton getBtnProximoRegistro() {
        return btnProximoRegistro;
    }

    public void setBtnProximoRegistro(javax.swing.JButton btnProximoRegistro) {
        this.btnProximoRegistro = btnProximoRegistro;
    }

    public javax.swing.JButton getBtnRegistroAnterior() {
        return btnRegistroAnterior;
    }

    public void setBtnRegistroAnterior(javax.swing.JButton btnRegistroAnterior) {
        this.btnRegistroAnterior = btnRegistroAnterior;
    }

    private static final Logger LOG = getLogger(CadastroFornecedorView.class.getName());
}
